version: 0.2

env:
  variables:
    VERSION: 0.0.0
  git-credential-helper: yes

phases:
  install:
    commands:
      - "curl -s -qL -o /usr/bin/jq https://https.naturalgateways.com/apps/jq"
      - "chmod +x /usr/bin/jq"
  pre_build:
    commands:
      - "json=$(jq -n --arg ver \"$VERSION\" '{version: $ver}')"
      - echo $json > dotnet/NaturalFacade.ApiServices/AppConfig.json
      - cat dotnet/NaturalFacade.ApiServices/AppConfig.json
      - rm dotnet/NuGet.config
  build:
    commands:
      - aws codeartifact login --tool dotnet --repository NaturalLibs --domain natural-libs --domain-owner 582929002414 --region ap-southeast-2
      - dotnet publish --configuration Release --runtime linux-x64 --self-contained false -p:PublishReadyToRun=true --output build dotnet/NaturalFacade.ApiLambdas/NaturalFacade.ApiLambdas.csproj
      - ls -l build
      - rm build/NaturalFacade.ApiLambdas.pdb
      - rm build/NaturalFacade.ApiServices.pdb
      - rm build/NaturalFacade.Common.pdb
  post_build:
    commands:
      - git tag "apibuilds/$VERSION"
      - git push origin --tags
artifacts:
  files:
    - build/*
  name: $VERSION.zip
  discard-paths: yes
